export const SET_INPUT_STATE = 'SET_INPUT_STATE';
export const SAVE_DATA = 'SAVE_DATA';
export const SEND_DATA_SUCCESS = 'SEND_DATA_SUCCESS';

//Homepage

export const FETCH_PROJECTS_DATA = 'FETCH_PROJECTS_DATA';